# WARNING: when making changes here, change also Dockerfile.desktop

FROM gradle:6.1-jdk8 as build

COPY --chown=gradle:gradle . /home/gradle/edu-car/car
WORKDIR /home/gradle/edu-car/car
RUN gradle installDist --no-daemon

FROM balenalib/raspberrypi3-alpine-openjdk:8-latest

COPY --from=build /home/gradle/edu-car/car/build/install/educar /opt/edu-car

RUN apk add wiringpi wiringpi-dev

EXPOSE 8080

CMD /opt/edu-car/bin/educar
