# WARNING: when making changes here, change also Dockerfile.desktop

FROM gradle:6.1-jdk8 as build

COPY --chown=gradle:gradle . /home/gradle/edu-car/car
WORKDIR /home/gradle/edu-car/car
RUN gradle installDist --no-daemon

FROM balenalib/raspberry-pi-openjdk:8-stretch-run

COPY --from=build /home/gradle/edu-car/car/build/install/educar /opt/edu-car

RUN git clone https://github.com/WiringPi/WiringPi.git &&\
  cd WiringPi && \
  ./build

EXPOSE 8080

CMD /opt/edu-car/bin/educar
